### ISSUE TITLE
issue/error python script to deploy sqlbigdata cluster

### ISSUE THREAD

**Issue by mataralhawiti** [Microsoft/sql-server-samples#502]
Python script to deploy SQL sever 2019 big data cluster on AKS always fails during sqlbigdata cluster creation.

the error is :

> Creating SQL Big Data cluster:sqlbigdata
> The license terms for this product can be downloaded from:
> - https://go.microsoft.com/fwlink/?LinkId=2002534
> 
> The privacy statement can be viewed at:
> - https://go.microsoft.com/fwlink/?LinkId=853010
> 
> NOTE: Cluster creation can take a significant amount of time depending on
> configuration, network speed, and the number of nodes in the cluster.
> 
> 2018-12-12 07:24:36.0251 UTC | INFO | Creating cluster...
**> error: the server doesn't have a resource type "sc"**
> Traceback (most recent call last):
>   File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\user\AppData\Local\Programs\Python\Python36\Scripts\mssqlctl.exe\__main__.py", line 9, in <module>
>   File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\mssqlctl\__init__.py", line 1249, in main
>     createCluster(args.name)
>   File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\mssqlctl\__init__.py", line 812, in createCluster
>     checkIfStorageClassesExist()
>   File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\mssqlctl\__init__.py", line 559, in checkIfStorageClassesExist
>     storage_class = check_output(["kubectl", "--context", os.environ['KUBECTL_CONTEXT'], "get", "sc", "-o=custom-columns=NAME:.metadata.name"])
>   File "c:\users\user\appdata\local\programs\python\python36\lib\subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "c:\users\user\appdata\local\programs\python\python36\lib\subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
**> subprocess.CalledProcessError: Command '['kubectl', '--context', 'sqlbigdata', 'get', 'sc', '-o=custom-columns=NAME:.metadata.name']' returned non-zero exit status 1.**

**Comment by twright-msft** [comment]
It appears that you dont have any storage classes defined which is unusual because in AKS the storage classes are created out of the box when you deploy an AKS cluster.  

Do you see any storage classes if you run this command?
`kubectl get sc`

You should see something like this:
```
NAME                PROVISIONER                AGE
default (default)   kubernetes.io/azure-disk   3d
managed-premium     kubernetes.io/azure-disk   3d
```
Those are the two storage classes that come out of the box.

Can you please share your environment variables (minus the passwords of course!)?

**Comment by mataralhawiti** [comment]
Hi Travis ,

I used all defaults environment variables in the script. The only change I did is i **AKS_NODE_COUNT** = 2 instead of 3 as I have some limitation on my Azure Account .


when i run `kubectl get sc` :
`NAME                PROVISIONER                AGE`
`default (default)   kubernetes.io/azure-disk   8m`
`managed-premium     kubernetes.io/azure-disk   8m`

**Comment by pradm** [comment]
is this deployment experience while using CTP 2.1 sql big data cluster builds or against CTP 2.2. The MSSQLCTL code which queries storage classes using direct kubectl commands was only present in ctp 2.1 build and it looks like we are trying to deploy ctp 2.2 build of sql big data cluster using ctp 2.1 build of MSSQLCTL utility. The latest version of mssqlctl can be installed using "pip3 install --extra-index-url https://private-repo.microsoft.com/python/ctp-2.2 mssqlctl" . When i look at the latest version of sql-server-samples/samples/features/sql-big-data-cluster/deployment/aks/deploy-sql-big-data-aks.py it has a definition of pulling latest sql on big data cluster images using the following variables.

DOCKER_REGISTRY="private-repo.microsoft.com"
DOCKER_REPOSITORY="mssql-private-preview"
DOCKER_IMAGE_TAG="latest"

So it looks like deployment is being tried against using MSSQLCTL build 2.1 against sql big data cluster build 2.2 which is failing. my suggestion would be delete the stale cluster -> upgrade mssqlctl to 2.2 build -> try the deployment again and validate if the issue gets resolved.

**Comment by pradm** [comment]
Along with this could you please also validate "kubectl version" and verify the server and client version are same for kubectl, if not please upgrade you client kubectl and make sure mssqlctl is of 2.2 build. Delete the stale sql big data cluster and then try redeploying and see if the issue gets solved. There was an occurrence of this issue when kubectl version had differences between client and server and upgrading solved the issue.

**Comment by pradm** [comment]
Could you please confirm what is the version of mssqlctl and kubectl on your client machine. In the past we have seen this issue when the client side kubectl version was different than the server side. On the same lines the CTP 2.2 mssqlctl utility has been updated to use k8s api’s instead of directly firing kubectl commands, since the error output is showing a kubectl command I am assuming you are
Using CTP 2.1 version of mssqlctl to deploy CTP 2.2 sql on big data clusters.

Actions:-
1.	Please validate kubectl version on the client side using “kubectl version” , if the client version is different than the server one please upgrade the client side tool and make sure the versions remain the same.
2.	Also make sure in the path kubectl binary path is set to the one that has been upgraded , it might so happen that on the client there are multiple versions of kubectl and the path might be pointing to an older version folder.
3.	Please upgrade mssqlctl to utilize ctp 2.2 version “pip3 install --extra-index-url https://private-repo.microsoft.com/python/ctp-2.2 mssqlctl”.
4.	Please delete the state failed sql on big data cluster only using mssqlctl delete option.
5.	Redeploy the sql on big data cluster using ctp 2.2 version of mssqlctl and confirm if the issue gets resolved.

**Comment by pradm** [comment]
Here is a sample of your error where mssqlctl is using kubectl version v1.5.1 and the deployment fails. it might also happen that you have the right version of kubectl under a specific folder but mssqlctl might be picking up kubectl from a different folder which might have an older version which might be causing this issue.

In this scenario i have version v1.10.8 in a folder and this path is correctly set, But i have a stale version of kubectl in c:\ root and when mssqlctl is getting launched from direct c:\ root its first traversing the root folder to see if the binary exists and its picking up from there.

One this part is taken care please make sure to utilize ctp 2.2 version of mssqlctl otherwise you will experience next set of failures as mssqlctl has also been updated in co-relation to sql big data binaries and incompatibilities between then will cause further issues.

Process Monitor Output

12/14/2018 12:46:16 AM    12:46:16.0388799 AM 1860   12708  kubectl.exe  IRP_MJ_CLOSE       SUCCESS      C:\kubectl.exe      10828  High          File System  C:\kubectl.exe              177                       
kubectl --context kubclusterctp22 get sc -o=custom-columns=NAME:.metadata.name       64-bit


C:\>kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"**v1.5.1**", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"**v1.11.5**", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

C:\>kubectl --context kubclusterctp22 get sc -o=custom-columns=Name:.metadata.name
the server doesn't have a resource type "sc"

C:\>mssqlctl create cluster sqlarisaksclusctp222 -v
2018-12-13 19:16:08.0876 UTC | DEBUG | Completed configuring logger()!
The license terms for this product can be downloaded from:
- https://go.microsoft.com/fwlink/?LinkId=2002534

The privacy statement can be viewed at:
- https://go.microsoft.com/fwlink/?LinkId=853010

NOTE: Cluster creation can take a significant amount of time depending on
configuration, network speed, and the number of nodes in the cluster.

2018-12-13 19:16:08.0893 UTC | INFO | Creating cluster...
the server doesn't have a resource type "sc"
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\mssqlctl.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\mssqlctl\__init__.py", line 1313, in main
    createCluster(args.name)
  File "c:\python37\lib\site-packages\mssqlctl\__init__.py", line 818, in createCluster
    checkIfStorageClassesExist()
  File "c:\python37\lib\site-packages\mssqlctl\__init__.py", line 565, in checkIfStorageClassesExist
    storage_class = check_output(["kubectl", "--context", os.environ['KUBECTL_CONTEXT'], "get", "sc", "-o=custom-columns=NAME:.metadata.name"])
  File "c:\python37\lib\subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "c:\python37\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['kubectl', '--context', 'kubclusterctp22', 'get', 'sc', '-o=custom-columns=NAME:.metadata.name']' returned non-zero exit status 1.

**Comment by mataralhawiti** [comment]
I'm still getting the same error even I'm using same Kubectl version in client and server, and running latest mssqlctl  version.

I followed the recommenced steps in previous comment



> C:\Users\user>kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T16:06:30Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.8", GitCommit:"7eab6a49736cc7b01869a15f9f05dc5b49efb9fc", GitTreeState:"clean", BuildDate:"2018-09-14T15:54:20Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by pradm** [comment]
That's strange as in the CTP 2.2 version of mssqlctl tool we have replaced the kubectl direct commands with API calls, Hence we should not see a direct call to (["kubectl", "--context", os.environ['KUBECTL_CONTEXT'], "get", "sc", "-o=custom-columns=NAME:.metadata.name"]). What is the version embedded in this file at your side xxx(python location)\Lib\site-packages\mssqlctl-15.0.1200.2998.post1.dist-info\metadata.json .

Since you are on windows machine could you please confirm by running process monitor which kubectl.exe is being referenced when mssqlctl is being executed and what is the version of the referenced kubectl.exe.

**Comment by mihaelablendea** [comment]
Indeed, from the call stack it seems you are using CTP2.1 version of mssqlctl. Try to uninstall it (pip3 uninstall mssqlctl) and install CTP2.2 using: pip3 install --extra-index-url https://private-repo.microsoft.com/python/ctp-2.2 mssqlctl.

Also, should double check you don't have another (older) version of kubectl that is being used. Most likely this is actually the issue.

**Comment by mataralhawiti** [comment]
Thank you guys, yes I found out that I was using old mssqlctl version.

However, creating sql clsuter will hang forever due to some autherization issues when it tries to pull off image from the repo.

Running `kubectl describe pod xxxxxxxxxxxxx` ..  I saw this in the log : 

> Failed to pull image "private-repo.microsoft.com/mssql-private-preview/mssql-controller:latest": rpc error: code = Unknown desc = Error response from daemon: unauthorized: authentication required



According to the [docs](https://docs.microsoft.com/en-us/sql/big-data-cluster/quickstart-big-data-cluster-deploy?view=sqlallproducts-allversions): 

>  Note
During the limited public preview, Docker credentials to download the SQL Server big data cluster images are provided to each customer by Microsoft. To request access, register here, and specify your interest to try SQL Server big data clusters.


There was no Docker credentials in the email I received from Microsoft when I initially request access EAP

**Comment by pradm** [comment]
Thank you so much for the update, Glad you could move ahead further. Pertaining to Docker credentials @mihaelablendea  will be able to help you on the same. Will request her to validate this further.

**Comment by pradm** [comment]
Could you please share your email id that has been provided for EAP Registration. @mihaelablendea will need to do some validation and will update you back.

**Comment by mihaelablendea** [comment]
Or feel free to reply to the confirmation email you got from Microsoft. Your assigned PM buddy should have beed cc-ed and they should know how to check your credentials and send them to you.

**Comment by mataralhawiti** [comment]
I've replied to email I got from EAP, hopefully I'll get this resolve soon.

**Comment by mataralhawiti** [comment]
I'm still waiting on EAP team to send me the docker credentials

**Comment by twright-msft** [comment]
@mataralhawiti - can you please send me your name/email address to twright @ microsoft [.] com?  I will follow up and see what the status is in the EAP system.  Thanks!
