### ISSUE TITLE
Access Denied while running Python script from sql server

### ISSUE THREAD

**Issue by KelloggJapan** [microsoft/sql-server-samples#701]
Hi ,
I am trying to call the python script from the sql server.
 EXEC sp_execute_external_script
    @language       = N'Python',
    @script         = N'import time
import sys
import codecs
import os
myfile = codecs.open(D:\SAP_Download\TPM_MATERIAL_MASTER_20191209_101848.txt, encoding=''utf-8'')
marylines = myfile.readlines()
myfile1 = codecs.open(D:\SAP_Download\TPM_MATERIAL_MASTER_20191209_101848.txt, ''w'', encoding=''utf-16'')
for line in marylines:
    myfile1.write(line)
myfile1.close()
myfile.close()';

And getting below error
A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
Msg 39019, Level 16, State 2, Line 8
An external script error occurred: 

Error in execution.  Check the output for more information.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\ProgramData\MSSQLSERVER\Temp-PY\Appcontainer1\5A4DD7D3-68C1-4299-8841-E3A74C93E65F\sqlindb_0.py", line 37
    myfile = codecs.open(D:\SAP_Download\TPM_MATERIAL_MASTER_20191209_101848.txt, encoding='utf-8')
                          ^
SyntaxError: invalid syntax

SqlSatelliteCall error: Error in execution.  Check the output for more information.
STDOUT message(s) from external script: 

Express Edition will continue to be enforced.
SqlSatelliteCall function failed. Please see the console output for more information.
Traceback (most recent call last):
  File "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 605, in rx_sql_satellite_call
    rx_native_call("SqlSatelliteCall", params)
  File "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 375, in rx_native_call
    ret = px_call(functionname, params)
RuntimeError: revoscalepy function failed.

**Comment by TjLuckyBastard** [comment]
I have the same issue.

```
EXECUTE sys.sp_execute_external_script	@language =N'Python'
					, @script = N'
					import numpy
					import pandas
					OutputDataSet = pandas.DataFrame(numpy.random.normal(sieze=100, loc=50, scale=3));'

					, @input_data_1 = N'     ;'

					WITH RESULT SETS(([Density] FLOAT NOT NULL));
```

this is actually example from Microsoft. When  I run it comes the same error
numpy and pandas are there, but comes error with import.

> > Msg 39004, Level 16, State 20, Line 0
> A 'Python' script error occurred during execution of 'sp_execute_external_script' with HRESULT 0x80004004.
> Msg 39019, Level 16, State 2, Line 0
> An external script error occurred: 
> 
> Error in execution.  Check the output for more information.
> Traceback (most recent call last):
>   File "<string>", line 3, in <module>
>   File "C:\ProgramData\SQLPLAYGROUND\Temp-PY\Appcontainer1\FF648E2B-CD69-4299-87DC-5BE7E3312AC9\sqlindb_0.py", line 31
>     import numpy
>     ^
> IndentationError: unexpected indent
> 
> SqlSatelliteCall error: Error in execution.  Check the output for more information.
> STDOUT message(s) from external script: 
> SqlSatelliteCall function failed. Please see the console output for more information.
> Traceback (most recent call last):
>   File "C:\Program Files\Microsoft SQL Server\MSSQL15.SQLPLAYGROUND\PYTHON_SERVICES\lib\site-packages\revoscalepy\computecontext\RxInSqlServer.py", line 605, in rx_sql_satellite_call
>     rx_native_call("SqlSatelliteCall", params)
>   File "C:\Program Files\Microsoft SQL Server\MSSQL15.SQLPLAYGROUND\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 375, in rx_native_call
>     ret = px_call(functionname, params)
> RuntimeError: revoscalepy function failed.
> 
> 
> Completion time: 
> 
> > 2020-05-24T18:54:40.1855956+02:00
